AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/**/**/*'
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
LineLength:
  Max: 100
Lint/HandleExceptions:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
